[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-args=-Tkernel/linker.ld --pie", "-Crelocation-model=pic"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
